CAAP2/CAAP2/Controllers/OrdersController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using AdvancedProgramming.Business;
using CAAP2.Business;
using CAAP2.Data;

namespace CAAP2.Controllers
{
    public class OrdersController : Controller
    {
        private OrderManager _manager = new OrderManager();
        private UserManager _userManager = new UserManager();

        // GET: Orders
        public ActionResult Index()
        {

            var orders = _manager.GetOrdersToProcess();
            var processingOrder = orders.FirstOrDefault(o => o.Status == "Processing");
            var model = new Tuple<IEnumerable<Order>, Order>(orders, processingOrder);
            return View(model);
        }

        // GET: Orders/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Order order = _manager.GetById((int)id);
            if (order == null)
            {
                return HttpNotFound();
            }
            return View(order);
        }

        // GET: Orders/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Orders/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "OrderID,UserID,OrderDetail,CreatedDate,Priority,TotalAmount,Status")] Order order)
        {
            if (ModelState.IsValid)
            {
                _manager.Add(order);
                _manager.Save();
                return RedirectToAction("Index");
            }

            return View(order);
        }

        // GET: Orders/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Order order = _manager.GetById((int)id);
            if (order == null)
            {
                return HttpNotFound();
            }
            ViewBag.Users = _userManager.GetAllUsers();
            return View(order);
        }

        // POST: Orders/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "OrderID,UserID,OrderDetail,CreatedDate,Priority,TotalAmount,Status")] Order order)
        {
            if (ModelState.IsValid)
            {
                _manager.Update(order);
                _manager.Save();
                return RedirectToAction("Index");
            }

            ViewBag.Users = _userManager.GetAllUsers();
            return View(order);
        }

        // GET: Orders/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Order order = _manager.GetById((int)id);
            if (order == null)
            {
                return HttpNotFound();
            }
            return View(order);
        }

        // POST: Orders/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Order order = _manager.GetById((int)id);
            _manager.Delete(id);
            _manager.Save();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                _manager.Dispose();
            }
            base.Dispose(disposing);
        }

        // GET: Orders/CurrentProcessing
        public PartialViewResult CurrentProcessing()
        {
            var processingOrders = _manager.GetAllOrders()
                .Where(o => o.Status == "Processing")
                .OrderBy(o => o.Priority)
                .ThenBy(o => o.CreatedDate)
                .ToList();

            if (processingOrders.Any())
            {
                processingOrders[0].IsBeingProcessed = true;
            }
            return PartialView("ProcessingOrderPartial", processingOrders);
        }


        // GET: Orders/CurrentPending
        public PartialViewResult CurrentPending()
        {
            var pendingOrders = _manager.GetAllOrders().Where(o => o.Status == "Pending").ToList();
            return PartialView("PendingOrderPartial", pendingOrders);
        }


        // POST: Orders/Execute
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Execute(int id)
        {
            Order order = _manager.GetById(id);

            if (order == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.NotFound);
            }
            if (order.Status == "Pending")
            {
                order.Status = "Processing";
                _manager.Update(order);
                _manager.Save();
                return new HttpStatusCodeResult(HttpStatusCode.OK);
            }
            else
            {
                return new HttpStatusCodeResult(HttpStatusCode.Forbidden, "La orden no se puede ejecutar.");
            }

            
        }

        // POST: Orders/Pause
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Pause(int id)
        {
            Order order = _manager.GetById(id);
            if (order == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.NotFound);
            }

            if (order.Status != "Processing")
            {
                order.Status = "Paused";
                _manager.Update(order);
                _manager.Save();
                return new HttpStatusCodeResult(HttpStatusCode.OK);
            }
            else
            {
                return new HttpStatusCodeResult(HttpStatusCode.Forbidden, "La orden está en procesamiento y no se puede pausar.");
            }
        }

        // GET: Orders/CurrentPaused
        public PartialViewResult CurrentPaused()
        {
            var pausedOrders = _manager.GetAllOrders().Where(o => o.Status == "Paused").ToList();
            return PartialView("PausedOrderPartial", pausedOrders);
        }

        // POST: Orders/Resume
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Resume(int id)
        {
            Order order = _manager.GetById(id);
            if (order == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.NotFound);
            }

            if (order.Status == "Paused")
            {
                order.Status = "Pending";
                _manager.Update(order);
                _manager.Save();
                return new HttpStatusCodeResult(HttpStatusCode.OK);
            }
            else
            {
                return new HttpStatusCodeResult(HttpStatusCode.Forbidden, "La orden no se pudo reanudar.");
            }
        }

        // POST: Orders/Cancel
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Cancel(int id)
        {
            Order order = _manager.GetById(id);
            if (order == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.NotFound);
            }

            if (order.Status != "Processing")
            {
                order.Status = "Cancelled";
                _manager.Update(order);
                _manager.Save();
                return new HttpStatusCodeResult(HttpStatusCode.OK);
            }
            else
            {
                return new HttpStatusCodeResult(HttpStatusCode.Forbidden, "La orden está en procesamiento y no se puede cancelar.");
            }
        }

        // POST: Orders/Cancel
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult CancelProcessing(int id)
        {
            Order order = _manager.GetById(id);
            if (order == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.NotFound);
            }

            if (!order.IsBeingProcessed)
            {
                order.Status = "Pending";
                _manager.Update(order);
                _manager.Save();
                return new HttpStatusCodeResult(HttpStatusCode.OK);
            }
            else
            {
                return new HttpStatusCodeResult(HttpStatusCode.Forbidden, "La orden está en procesamiento y no se puede cancelar.");
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult AdvanceProcessingQueue()
        {
            var processingOrders = _manager.GetAllOrders()
                .Where(o => o.Status == "Processing")
                .OrderBy(o => o.Priority)
                .ThenBy(o => o.CreatedDate)
                .ToList();

            if (processingOrders.Any())
            {
                var current = processingOrders[0];
                current.Status = "Processed";
                _manager.Update(current);

                if (processingOrders.Count > 1)
                {
                    var next = processingOrders[1];
                }

                _manager.Save();
            }

            return new HttpStatusCodeResult(HttpStatusCode.OK);
        }


    }
}

CAAP2/CAAP2/Views/Orders/Create.cshtml
@model CAAP2.Data.Order

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Order</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.UserID, "UserID", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("UserID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.UserID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.OrderDetail, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.OrderDetail, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.OrderDetail, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CreatedDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CreatedDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CreatedDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Priority, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Priority, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Priority, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TotalAmount, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TotalAmount, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TotalAmount, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Status, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Status, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Status, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

CAAP2/CAAP2/Views/Orders/Delete.cshtml
@model CAAP2.Data.Order

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Order</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.OrderDetail)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.OrderDetail)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CreatedDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CreatedDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Priority)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Priority)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TotalAmount)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TotalAmount)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Status)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Status)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.User.FullName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.User.FullName)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

CAAP2/CAAP2/Views/Orders/Details.cshtml
@model CAAP2.Data.Order

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Order</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.OrderDetail)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.OrderDetail)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CreatedDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CreatedDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Priority)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Priority)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TotalAmount)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TotalAmount)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Status)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Status)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.User.FullName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.User.FullName)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.OrderID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

CAAP2/CAAP2/Views/Orders/Edit.cshtml
@model CAAP2.Data.Order

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Order</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.OrderID)

        <div class="form-group">
            @Html.LabelFor(model => model.UserID, "UserID", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(
                    model => model.UserID,
                    new SelectList((IEnumerable<CAAP2.Data.User>)ViewBag.Users, "UserID", "FullName", Model.UserID),
                    "-- Seleccione un usuario --",
                    new { @class = "form-control" }
                )
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.OrderDetail, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.OrderDetail, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.OrderDetail, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CreatedDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CreatedDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CreatedDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Priority, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Priority, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Priority, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TotalAmount, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TotalAmount, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TotalAmount, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Status, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Status, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Status, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

CAAP2/CAAP2/Views/Orders/Index.cshtml
@model Tuple<IEnumerable<CAAP2.Data.Order>, CAAP2.Data.Order>

@{
    ViewBag.Title = "Órdenes";
}
@Html.AntiForgeryToken()
<div class="container mt-4">
    <div class="row">
        <div class="col-md-9">
            <h3 class="mb-3 text-success"><i class="fa fa-utensils me-2"></i> Órdenes </h3>
            <table class="table table-bordered table-hover bg-white shadow-sm rounded">
                <thead class="thead-light">
                    <tr>
                        <th><i class="fa fa-hashtag"></i> Orden</th>
                        <th><i class="fa fa-info-circle"></i> Detalle</th>
                        <th><i class="fa fa-calendar-alt"></i> Fecha</th>
                        <th><i class="fa fa-exclamation-triangle text-warning"></i> Prioridad</th>
                        <th><i class="fa fa-user"></i> Cliente</th>
                        <th><i class="fa fa-star text-warning"></i> Premium</th>
                        <th><i class="fa fa-check-circle text-info"></i> Estado</th>
                        <th><i class="fa fa-tools"></i> Acciones</th>
                    </tr>
                </thead>
                <tbody id="pendingOrdersBody">
                    @Html.Partial("PendingOrderPartial", Model.Item1.Where(o => o.Status == "Pending"))
                </tbody>
            </table>
        </div>

        <div class="col-md-3">
            <div class="card mb-4 shadow rounded">
                <div class="card-header bg-warning text-dark d-flex justify-content-between align-items-center">
                    <h5 class="mb-0"><i class="fa fa-fire me-2"></i> Preparando</h5>
                    <button class="btn btn-outline-dark btn-sm" onclick="advanceAndRefresh()" title="Avanzar preparación">
                        <i class="fa fa-forward"></i>
                    </button>
                </div>
                <div class="card-body bg-light" id="processingOrderDiv">
                    @Html.Partial("ProcessingOrderPartial", Model.Item1.Where(o => o.Status == "Processing"))
                </div>
            </div>

            <div class="card shadow rounded">
                <div class="card-header bg-secondary text-white">
                    <h5 class="mb-0"><i class="fa fa-pause-circle me-2"></i> En Espera</h5>
                </div>
                <div class="card-body bg-light" id="pausedOrderDiv">
                    @Html.Partial("PausedOrderPartial", Model.Item1.Where(o => o.Status == "Paused"))
                </div>
            </div>
        </div>
    </div>
</div>

@section Scripts {
    <script>
        // ... (Las funciones JavaScript permanecen sin cambios)
        function executeOrder(id) {
            if (!confirm("¿Marcar orden como en preparación?")) return;
            const token = $('input[name="__RequestVerificationToken"]').val();
            fetch('@Url.Action("Execute", "Orders")', {
                method: 'POST',
                headers: {
                    'Content-Type': 'application/x-www-form-urlencoded',
                    'RequestVerificationToken': $('input[name="__RequestVerificationToken"]').val()
                },
                body: `id=${id}&__RequestVerificationToken=${token}`
            })
            .then(response => {
                if (response.ok) {
                    document.getElementById("status-" + id).innerText = "Preparando";
                    document.getElementById("order-row-" + id).remove();
                    refreshProcessingOrder();
                    refreshPendingOrders();
                } else {
                    alert("No se pudo marcar la orden.");
                }
            });
        }

        function refreshProcessingOrder() {
            fetch('@Url.Action("CurrentProcessing", "Orders")')
            .then(response => response.text())
            .then(html => {
                document.getElementById("processingOrderDiv").innerHTML = html;
            });
        }

        function cancelOrder(id) {
            if (!confirm("¿Cancelar esta orden?")) return;
            const token = $('input[name="__RequestVerificationToken"]').val();
            fetch('@Url.Action("Cancel", "Orders")', {
                method: 'POST',
                headers: {
                    'Content-Type': 'application/x-www-form-urlencoded',
                    'RequestVerificationToken': $('input[name="__RequestVerificationToken"]').val()
                },
                body: `id=${id}&__RequestVerificationToken=${token}`
            })
            .then(response => {
                if (response.ok) {
                    refreshProcessingOrder();
                    refreshPendingOrders();
                } else {
                    alert("No se pudo cancelar la orden.");
                }
            });
        }

        function cancelOrderProcessing(id) {
            if (!confirm("¿Devolver orden a pendientes?")) return;
            const token = $('input[name="__RequestVerificationToken"]').val();
            fetch('@Url.Action("CancelProcessing", "Orders")', {
                method: 'POST',
                headers: {
                    'Content-Type': 'application/x-www-form-urlencoded',
                    'RequestVerificationToken': $('input[name="__RequestVerificationToken"]').val()
                },
                body: `id=${id}&__RequestVerificationToken=${token}`
            })
            .then(response => {
                if (response.ok) {
                    refreshProcessingOrder();
                    refreshPendingOrders();
                } else {
                    alert("No se pudo devolver la orden.");
                }
            });
        }

        function pauseOrder(id) {
            if (!confirm("¿Poner orden en espera?")) return;
            const token = $('input[name="__RequestVerificationToken"]').val();
            fetch('@Url.Action("Pause", "Orders")', {
                method: 'POST',
                headers: {
                    'Content-Type': 'application/x-www-form-urlencoded',
                    'RequestVerificationToken': $('input[name="__RequestVerificationToken"]').val()
                },
                body: `id=${id}&__RequestVerificationToken=${token}`
            })
            .then(response => {
                if (response.ok) {
                    document.getElementById("status-" + id).innerText = "En Espera";
                    refreshPausedOrder();
                    refreshPendingOrders();
                } else {
                    alert("No se puede poner en espera una orden en preparación.");
                }
            });
        }

        function refreshPausedOrder() {
            fetch('@Url.Action("CurrentPaused", "Orders")')
                .then(response => response.text())
                .then(html => {
                    document.getElementById("pausedOrderDiv").innerHTML = html;
                });
        }

        function resumeOrder(id) {
            const token = $('input[name="__RequestVerificationToken"]').val();
            fetch('@Url.Action("Resume", "Orders")', {
                method: 'POST',
                headers: {
                    'Content-Type': 'application/x-www-form-urlencoded',
                    'RequestVerificationToken': $('input[name="__RequestVerificationToken"]').val()
                },
                body: `id=${id}&__RequestVerificationToken=${token}`
            })
            .then(response => {
                if (response.ok) {
                    refreshPausedOrder();
                    refreshPendingOrders();
                } else {
                    alert("No se pudo reanudar.");
                }
            });
        }

        function refreshPendingOrders() {
            fetch('@Url.Action("CurrentPending", "Orders")')
                .then(response => response.text())
                .then(html => {
                    document.getElementById("pendingOrdersBody").innerHTML = html;
                });
        }

        function advanceAndRefresh() {
            const token = $('input[name="__RequestVerificationToken"]').val();

            fetch('@Url.Action("AdvanceProcessingQueue", "Orders")', {
                method: 'POST',
                headers: {
                    'Content-Type': 'application/x-www-form-urlencoded',
                    'RequestVerificationToken': token
                },
                body: `__RequestVerificationToken=${token}`
            })
            .then(response => {
                if (response.ok) {
                    refreshProcessingOrder();
                    refreshPendingOrders();
                } else {
                    alert("No se pudo avanzar la cola de preparación.");
                }
            });
        }
    </script>
}

CAAP2/CAAP2/Views/Orders/PausedOrderPartial.cshtml
@model IEnumerable<CAAP2.Data.Order>

@if (Model != null && Model.Any())
{
    <div class="card mt-4">
        <div class="card-header bg-warning text-dark">
            Pausadas
        </div>
        <ul class="list-group list-group-flush">
            @foreach (var order in Model)
            {
                <li class="list-group-item d-flex justify-content-between align-items-center">
                    <div>
                        <strong>#@order.OrderID</strong> - @order.OrderDetail <br />
                        <small>Prioridad: @order.Priority | Cliente: @order.User.FullName</small>
                        <small>Estado: @order.Status</small>
                    </div>
                    <button class="btn btn-danger btn-sm" onclick="resumeOrder(@order.OrderID)">Reanudar</button>
                </li>
            }
        </ul>
    </div>

}
else
{
    <div class="alert alert-info">No hay ninguna orden en pausa.</div>
}

CAAP2/CAAP2/Views/Orders/PendingOrderPartial.cshtml
@model IEnumerable<CAAP2.Data.Order>

@foreach (var order in Model)
{
    <tr id="order-row-@order.OrderID">
        <td>@order.OrderID</td>
        <td>@order.OrderDetail</td>
        <td>@(order.CreatedDate?.ToString("g"))</td>
        <td>@order.Priority</td>
        <td>@order.User.FullName</td>
        <td>@(order.User.IsPremium == true ? "Yes" : "No")</td>
        <td id="status-@order.OrderID">@order.Status</td>
        <td>
            <div class="d-flex flex-wrap gap-1">
                <button class="btn btn-success btn-sm" onclick="executeOrder(@order.OrderID)">
                    Ejecutar
                </button>
                <button class="btn btn-warning btn-sm" onclick="pauseOrder(@order.OrderID)">
                    Pausar
                </button>
                <button class="btn btn-danger btn-sm" onclick="cancelOrder(@order.OrderID)">
                    Cancelar
                </button>
                <a href="@Url.Action("Details", "Orders", new { id = order.OrderID })" class="btn btn-info btn-sm">
                    Detalle
                </a>
                <a href="@Url.Action("Edit", "Orders", new { id = order.OrderID })" class="btn btn-primary btn-sm">
                    Modificar
                </a>
            </div>
        </td>
    </tr>
}